/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PropertyType = IDL.Variant({
  'retail' : IDL.Null,
  'commercial' : IDL.Null,
  'other' : IDL.Null,
  'investment' : IDL.Null,
  'office' : IDL.Null,
});
export const Consultation = IDL.Record({
  'id' : IDL.Nat,
  'propertyType' : PropertyType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const ConsultationRequest = IDL.Record({
  'propertyType' : PropertyType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const SubmissionResult = IDL.Record({
  'id' : IDL.Nat,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'listConsultations' : IDL.Func([], [IDL.Vec(Consultation)], ['query']),
  'submitConsultation' : IDL.Func(
      [ConsultationRequest],
      [SubmissionResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PropertyType = IDL.Variant({
    'retail' : IDL.Null,
    'commercial' : IDL.Null,
    'other' : IDL.Null,
    'investment' : IDL.Null,
    'office' : IDL.Null,
  });
  const Consultation = IDL.Record({
    'id' : IDL.Nat,
    'propertyType' : PropertyType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const ConsultationRequest = IDL.Record({
    'propertyType' : PropertyType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SubmissionResult = IDL.Record({ 'id' : IDL.Nat, 'message' : IDL.Text });
  
  return IDL.Service({
    'listConsultations' : IDL.Func([], [IDL.Vec(Consultation)], ['query']),
    'submitConsultation' : IDL.Func(
        [ConsultationRequest],
        [SubmissionResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };