/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Consultation {
  'id' : bigint,
  'propertyType' : PropertyType,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface ConsultationRequest {
  'propertyType' : PropertyType,
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export type PropertyType = { 'retail' : null } |
  { 'commercial' : null } |
  { 'other' : null } |
  { 'investment' : null } |
  { 'office' : null };
export interface SubmissionResult { 'id' : bigint, 'message' : string }
export interface _SERVICE {
  'listConsultations' : ActorMethod<[], Array<Consultation>>,
  'submitConsultation' : ActorMethod<[ConsultationRequest], SubmissionResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];