/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ConsultationRequest {
    propertyType: PropertyType;
    name: string;
    email: string;
    message: string;
    phone: string;
}
export interface SubmissionResult {
    id: bigint;
    message: string;
}
export interface Consultation {
    id: bigint;
    propertyType: PropertyType;
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
    phone: string;
}
export enum PropertyType {
    retail = "retail",
    commercial = "commercial",
    other = "other",
    investment = "investment",
    office = "office"
}
export interface backendInterface {
    listConsultations(): Promise<Array<Consultation>>;
    submitConsultation(req: ConsultationRequest): Promise<SubmissionResult>;
}
import type { Consultation as _Consultation, ConsultationRequest as _ConsultationRequest, PropertyType as _PropertyType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async listConsultations(): Promise<Array<Consultation>> {
        if (this.processError) {
            try {
                const result = await this.actor.listConsultations();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listConsultations();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitConsultation(arg0: ConsultationRequest): Promise<SubmissionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitConsultation(to_candid_ConsultationRequest_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitConsultation(to_candid_ConsultationRequest_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Consultation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Consultation): Consultation {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyType): PropertyType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    propertyType: _PropertyType;
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
    phone: string;
}): {
    id: bigint;
    propertyType: PropertyType;
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
    phone: string;
} {
    return {
        id: value.id,
        propertyType: from_candid_PropertyType_n4(_uploadFile, _downloadFile, value.propertyType),
        name: value.name,
        email: value.email,
        message: value.message,
        timestamp: value.timestamp,
        phone: value.phone
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    retail: null;
} | {
    commercial: null;
} | {
    other: null;
} | {
    investment: null;
} | {
    office: null;
}): PropertyType {
    return "retail" in value ? PropertyType.retail : "commercial" in value ? PropertyType.commercial : "other" in value ? PropertyType.other : "investment" in value ? PropertyType.investment : "office" in value ? PropertyType.office : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Consultation>): Array<Consultation> {
    return value.map((x)=>from_candid_Consultation_n2(_uploadFile, _downloadFile, x));
}
function to_candid_ConsultationRequest_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConsultationRequest): _ConsultationRequest {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): _PropertyType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    propertyType: PropertyType;
    name: string;
    email: string;
    message: string;
    phone: string;
}): {
    propertyType: _PropertyType;
    name: string;
    email: string;
    message: string;
    phone: string;
} {
    return {
        propertyType: to_candid_PropertyType_n8(_uploadFile, _downloadFile, value.propertyType),
        name: value.name,
        email: value.email,
        message: value.message,
        phone: value.phone
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): {
    retail: null;
} | {
    commercial: null;
} | {
    other: null;
} | {
    investment: null;
} | {
    office: null;
} {
    return value == PropertyType.retail ? {
        retail: null
    } : value == PropertyType.commercial ? {
        commercial: null
    } : value == PropertyType.other ? {
        other: null
    } : value == PropertyType.investment ? {
        investment: null
    } : value == PropertyType.office ? {
        office: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
